### ISSUE TITLE
webpack.config.babel.js Unexpected token import

### ISSUE THREAD

**Issue by sallespro** [developit/preact-www#67] opened 2016-12-11 13:50 UTC
i'd appretiate a double check in webpack.config.js. i'm not a seasoned `webpacker` and it seems it has this import / loader issues.

```
webpack.config.babel.js:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

**Comment by developit** [comment] 2016-12-11 16:38
How are you loading it? The file being called `webpack.config.babel.js` makes Webpack 0.13+ preprocess it with Babel.

**Comment by sallespro** [comment] 2016-12-11 16:55
hi, i am following straight install instructions. first it missed `ncp` module, and then i got into this error.
tried `babel-loader` then .babelrc presets, not sure what is missing.

i do mean webpack.config.babel.js.

Em 11/12/2016, à(s) 14:38, Jason Miller <notifications@github.com> escreveu:

**Comment by developit** [comment] 2016-12-11 17:15
What version of npm are you using?

`npm -v && npm ls --depth 1`

**Comment by sallespro** [comment] 2016-12-11 17:30
```
3.8.3
preact@1.0.0 /home/user/dev/preact
├─┬ autoprefixer@6.5.3
│ ├── browserslist@1.4.0
│ ├── caniuse-db@1.0.30000597
│ ├── normalize-range@0.1.2
│ ├── num2fraction@1.2.2
│ ├── postcss@5.2.6
│ └── postcss-value-parser@3.3.0
├── babel@6.5.2
├─┬ babel-core@6.20.0
│ ├── babel-code-frame@6.20.0
│ ├── babel-generator@6.20.0
│ ├── babel-helpers@6.16.0
│ ├── babel-messages@6.8.0
│ ├── babel-template@6.16.0
│ ├── babel-traverse@6.20.0
│ ├── babel-types@6.20.0
│ ├── babylon@6.14.1
│ ├── convert-source-map@1.3.0
│ ├── debug@2.3.3
│ ├── json5@0.5.1
│ ├── lodash@4.17.2
│ ├── minimatch@3.0.3
│ ├── path-is-absolute@1.0.1
│ ├── private@0.1.6
│ ├── slash@1.0.0
│ └── source-map@0.5.6
├─┬ babel-eslint@7.1.1
│ └── lodash.pickby@4.6.0
├─┬ babel-loader@6.2.9
│ ├── find-cache-dir@0.1.1
│ ├── loader-utils@0.2.16
│ └── object-assign@4.1.0
├─┬ babel-plugin-transform-decorators-legacy@1.3.4
│ └── babel-plugin-syntax-decorators@6.13.0
├─┬ babel-plugin-transform-react-jsx@6.8.0
│ ├── babel-helper-builder-react-jsx@6.18.0
│ └── babel-plugin-syntax-jsx@6.18.0
├─┬ babel-preset-es2015@6.18.0
│ ├── babel-plugin-check-es2015-constants@6.8.0
│ ├── babel-plugin-transform-es2015-arrow-functions@6.8.0
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.8.0
│ ├── babel-plugin-transform-es2015-block-scoping@6.20.0
│ ├── babel-plugin-transform-es2015-classes@6.18.0
│ ├── babel-plugin-transform-es2015-computed-properties@6.8.0
│ ├── babel-plugin-transform-es2015-destructuring@6.19.0
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.8.0
│ ├── babel-plugin-transform-es2015-for-of@6.18.0
│ ├── babel-plugin-transform-es2015-function-name@6.9.0
│ ├── babel-plugin-transform-es2015-literals@6.8.0
│ ├── babel-plugin-transform-es2015-modules-amd@6.18.0
│ ├── babel-plugin-transform-es2015-modules-commonjs@6.18.0
│ ├── babel-plugin-transform-es2015-modules-systemjs@6.19.0
│ ├── babel-plugin-transform-es2015-modules-umd@6.18.0
│ ├── babel-plugin-transform-es2015-object-super@6.8.0
│ ├── babel-plugin-transform-es2015-parameters@6.18.0
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.18.0
│ ├── babel-plugin-transform-es2015-spread@6.8.0
│ ├── babel-plugin-transform-es2015-sticky-regex@6.8.0
│ ├── babel-plugin-transform-es2015-template-literals@6.8.0
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.18.0
│ ├── babel-plugin-transform-es2015-unicode-regex@6.11.0
│ └── babel-plugin-transform-regenerator@6.20.0
├─┬ babel-preset-es2015-minimal@2.1.0
│ └── modify-babel-preset@3.2.0
├─┬ babel-preset-stage-0@6.16.0
│ ├── babel-plugin-transform-do-expressions@6.8.0
│ ├── babel-plugin-transform-function-bind@6.8.0
│ └── babel-preset-stage-1@6.16.0
├─┬ babel-register@6.18.0
│ ├── home-or-tmp@2.0.0
│ └── source-map-support@0.4.6
├─┬ babel-runtime@6.20.0
│ └── regenerator-runtime@0.10.1
├─┬ chai@3.5.0
│ ├── assertion-error@1.0.2
│ ├── deep-eql@0.1.3
│ └── type-detect@1.0.0
├─┬ copy-webpack-plugin@4.0.1
│ ├── bluebird@2.11.0
│ ├── fs-extra@0.26.7
│ ├── glob@6.0.4
│ ├── is-glob@3.1.0
│ └── node-dir@0.1.16
├── core-js@2.4.1
├─┬ cross-env@2.0.1
│ ├── cross-spawn@3.0.1
│ └── lodash.assign@3.2.0
├─┬ css-loader@0.25.0
│ ├── css-selector-tokenizer@0.6.0
│ ├── cssnano@3.8.2
│ ├── lodash.camelcase@3.0.1
│ ├── postcss-modules-extract-imports@1.0.1
│ ├── postcss-modules-local-by-default@1.1.1
│ ├── postcss-modules-scope@1.0.2
│ ├── postcss-modules-values@1.2.2
│ └── source-list-map@0.1.7
├─┬ eslint@3.12.0
│ ├── chalk@1.1.3
│ ├── concat-stream@1.5.2
│ ├── doctrine@1.5.0
│ ├── escope@3.6.0
│ ├── espree@3.3.2
│ ├── estraverse@4.2.0
│ ├── esutils@2.0.2
│ ├── file-entry-cache@2.0.0
│ ├── glob@7.1.1
│ ├── globals@9.14.0
│ ├── ignore@3.2.0
│ ├── imurmurhash@0.1.4
│ ├── inquirer@0.12.0
│ ├── is-my-json-valid@2.15.0
│ ├── is-resolvable@1.0.0
│ ├── js-yaml@3.6.1
│ ├── json-stable-stringify@1.0.1
│ ├── levn@0.3.0
│ ├── natural-compare@1.4.0
│ ├── optionator@0.8.2
│ ├── path-is-inside@1.0.2
│ ├── pluralize@1.2.1
│ ├── progress@1.1.8
│ ├── require-uncached@1.0.3
│ ├── shelljs@0.7.5
│ ├── strip-bom@3.0.0
│ ├── strip-json-comments@1.0.4
│ ├── table@3.8.3
│ ├── text-table@0.2.0
│ └── user-home@2.0.0
├─┬ extract-text-webpack-plugin@1.0.1
│ ├── async@1.5.2
│ └── webpack-sources@0.1.3
├── file-loader@0.9.0
├─┬ html-webpack-plugin@2.24.1
│ ├── bluebird@3.4.6
│ ├── html-minifier@3.2.3
│ ├── pretty-error@2.0.2
│ └── toposort@1.0.0
├── json-loader@0.5.4
├─┬ karma@1.3.0
│ ├── bluebird@3.4.6
│ ├── body-parser@1.15.2
│ ├── chokidar@1.6.1
│ ├── colors@1.1.2
│ ├── combine-lists@1.0.1
│ ├── connect@3.5.0
│ ├── di@0.0.1
│ ├── dom-serialize@2.2.1
│ ├── expand-braces@0.1.2
│ ├── glob@7.1.1
│ ├── graceful-fs@4.1.11
│ ├── http-proxy@1.16.2
│ ├── isbinaryfile@3.0.1
│ ├── lodash@3.10.1
│ ├── log4js@0.6.38
│ ├── mime@1.3.4
│ ├── optimist@0.6.1
│ ├── qjobs@1.1.5
│ ├── range-parser@1.2.0
│ ├── rimraf@2.5.4
│ ├── socket.io@1.4.7
│ ├── tmp@0.0.28
│ └── useragent@2.1.9
├── karma-chai@0.1.0
├── karma-chai-sinon@0.1.5
├─┬ karma-mocha@1.3.0
│ └── minimist@1.2.0
├── karma-mocha-reporter@2.2.1
├── karma-phantomjs-launcher@1.0.2
├── karma-sourcemap-loader@0.3.7
├─┬ karma-webpack@1.8.0
│ ├── async@0.9.2
│ ├── lodash@3.10.1
│ ├── source-map@0.1.43
│ └── webpack-dev-middleware@1.8.4
├─┬ less@2.7.1
│ ├── errno@0.1.4
│ ├── image-size@0.5.0
│ └── promise@7.1.1
├── less-loader@2.2.3
├─┬ mkdirp@0.5.1
│ └── minimist@0.0.8
├─┬ mocha@3.2.0
│ ├── browser-stdout@1.3.0
│ ├── commander@2.9.0
│ ├── debug@2.2.0
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.5
│ ├── glob@7.0.5
│ ├── growl@1.9.2
│ ├── json3@3.3.2
│ ├── lodash.create@3.1.1
│ └── supports-color@3.1.2
├── ncp@2.0.0
├─┬ offline-plugin@4.5.3
│ ├── deep-extend@0.4.1
│ └── ejs@2.5.5
├─┬ path@0.12.7
│ ├── process@0.11.9
│ └── util@0.10.3
├─┬ phantomjs-prebuilt@2.1.14
│ ├── es6-promise@4.0.5
│ ├── extract-zip@1.5.0
│ ├── fs-extra@1.0.0
│ ├── hasha@2.2.0
│ ├── kew@0.7.0
│ ├── request@2.79.0
│ ├── request-progress@2.0.1
│ └── which@1.2.12
├── postcss-loader@0.13.0
├── preact@6.4.0
├─┬ preact-compat@3.9.4
│ ├── preact-render-to-string@3.3.0
│ └── preact-transition-group@1.1.0
├── preact-router@2.3.2
├── proptypes@0.14.3
├── raw-loader@0.5.1
├─┬ sinon@1.17.6
│ ├── formatio@1.1.1
│ ├── lolex@1.3.2
│ └── samsam@1.1.2
├── sinon-chai@2.8.0
├─┬ source-map-loader@0.1.5
│ ├── async@0.9.2
│ └── source-map@0.1.43
├── style-loader@0.13.1
├─┬ superstatic@4.0.3
│ ├── as-array@2.0.0
│ ├── basic-auth-connect@1.0.0
│ ├── char-spinner@1.0.1
│ ├── compare-semver@1.1.0
│ ├── compression@1.6.2
│ ├── connect-query@0.2.0
│ ├── destroy@1.0.4
│ ├── fast-url-parser@1.1.3
│ ├── fs-extra@0.30.0
│ ├── glob@7.1.1
│ ├── glob-slasher@1.0.1
│ ├── home-dir@1.0.0
│ ├── is-url@1.2.2
│ ├── join-path@1.1.0
│ ├── mime-types@2.1.13
│ ├── morgan@1.7.0
│ ├── nash@2.0.4
│ ├── on-finished@2.3.0
│ ├── on-headers@1.0.1
│ ├── path-to-regexp@1.7.0
│ ├── router@1.1.4
│ ├── rsvp@3.3.3
│ ├── string-length@1.0.1
│ ├── try-require@1.2.1
│ └── update-notifier@1.0.3
├─┬ url-loader@0.5.7
│ └── mime@1.2.11
├─┬ webpack@1.14.0
│ ├── acorn@3.3.0
│ ├── clone@1.0.2
│ ├── enhanced-resolve@0.9.1
│ ├── interpret@0.6.6
│ ├── memory-fs@0.3.0
│ ├── node-libs-browser@0.7.0
│ ├── tapable@0.1.10
│ ├── uglify-js@2.7.5
│ ├── watchpack@0.2.9
│ └── webpack-core@0.6.9
└─┬ webpack-dev-server@1.16.2
  ├── connect-history-api-fallback@1.3.0
  ├── express@4.14.0
  ├── http-proxy-middleware@0.17.3
  ├── open@0.0.5
  ├── serve-index@1.8.0
  ├── sockjs@0.3.18
  ├── sockjs-client@1.1.1
  ├── stream-cache@0.0.2
  └── strip-ansi@3.0.1
```

**Comment by developit** [comment] 2016-12-12 14:55
Try a fresh clone. I just did and it works fine - it seems like your babelrc is messed up, which makes Webpack unable to transpile `webpack.config.babel.js`.

**Comment by developit** [comment] 2017-01-04 13:34
Closing for now since I couldn't reproduce, but feel free to re-open.

**Closed by developit** 2017-01-04 13:34 UTC

**Comment by sbussard** [comment] 2017-02-22 22:57
This .babelrc file will do it

```
{
  "presets": [
    ["es2015", {"modules": false}],
    "react",
    "stage-2"
  ],
  "plugins": [
    ["babel-root-import", {"rootPathSuffix": "src"}],
    ["transform-runtime", {"polyfill": false, "regenerator": true}]
  ]
}
```

**Comment by developit** [comment] 2017-02-23 00:12
Right, would be a webpack 2 thing.  That's why this project uses webpack 1 :P
